name: Setup
description: Setup environment

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install dependencies (Ubuntu only)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    - name: Install
      shell: bash
      run: pnpm i
